### ISSUE TITLE
Include Glyphicons fonts?

### ISSUE THREAD

**Issue by currentuser** [DrTom/bootswatch-sprockets#1]
Is it technically possible to include glyphicons fonts?

After installing `bootswatch-sprockets` (for a [ruby website](http://www.currentuser.io) built with [middleman](https://github.com/middleman/middleman)), I had to add a link to a CDN, as indicated here : http://www.andyjarrett.co.uk/2013/09/26/glyphicons-and-bootswatch-themes-from-cdn

Maybe it can be avoided?

BTW: Thanks for your work!

**Comment by DrTom** [comment]
Certainly. Though it is actually not related to bootswatch-sprockets. The fonts come with bootstap-sass. The documentation has a section on the matter https://github.com/twbs/bootstrap-sass#fonts. 

I prefer FontAwesome as in the following project https://github.com/json-roa/json-roa_browser_source.  The [Gemfile](https://github.com/json-roa/json-roa_browser_source/blob/master/Gemfile) and [main.css.sass](https://github.com/json-roa/json-roa_browser_source/blob/master/source/assets/stylesheets/main.css.sass) are relevant as a woking example.

**Comment by currentuser** [comment]
My understanding of the problem is limited and I am not sure to understand what I can do.

My website perfectly worked with glyphicons and Bootstrap (with 'bootstrap-sass' gem) and Middleman.

Then I followed the documentation of 'bootswatch-sprockets' (because I wanted to use a theme), and glyphicons suddenly weren't correctly displayed anymore.

The only solution I found, till now, is to use the solution I mentionned.

If you think of another solution, I think you could mention it in the 'bootswatch-sprockets' documentation because I guess I won't be the only one to have the same problem that arises when trying to use this gem (even if the gem is not the source of the problem).

**Comment by DrTom** [comment]
As I said, bootswatch-sprockets doesn't interfere with assets paths or similar, you can have look in the `lib` folder, there is nothing ;-) 

Can you please check if the `bootstrap-sass` gem got upgraded (via the history of Gemfile.lock)?
As far as I remember there was some change within `bootstrap-sass`.

**Comment by currentuser** [comment]
No, `bootstrap-sass` was, and still is, in version `3.3.1.0`, the latest. I just tried with version `3.2.0.2` with the same result.

Apparently the problem occurs when I add `@import bootswatch/slate/variables` in my `application.css.sass` file (before `@import bootstrap-sprockets`, as indicated in the `README`). As soon as I comment this line, the problem with Glyphicons disappears.

I'm trying to narrow the problem. Without the line `@import bootswatch/slate/variables`, the browser loads the url http://0.0.0.0:4567/fonts/bootstrap/glyphicons-halflings-regular.woff (with success). With the line, the browser loads http://0.0.0.0:4567/fonts/glyphicons-halflings-regular.woff (and fails).

I guess, it's due to the following line in `bootswatch-sprockets-0.1.1/assets/stylesheets/bootswatch/slate/_variables.scss`:

``` scss
$icon-font-path:          "../fonts/";
```

compared to the following line in `bootstrap-sass-3.3.1.0/assets/stylesheets/bootstrap/_variables.scss`

``` scss
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../fonts/bootstrap/") !default;
```

Note: I'm just making observations, I don't know what is right or wrong.

**Comment by DrTom** [comment]
Yes, you found the issue. The icon-font-path reset is from the original bootswatch but it doesn't play well with sprockets. 

I pushed a fix. Please try version 1.0.0.

**Comment by currentuser** [comment]
I removed the link to the CDN in my website and it works great now with version 1.0.0!
